variable name {}
variable domain {}
variable host {}
variable vpc_id {}
variable vpc_cidr_block {}
variable private_subnet_ids {}
variable target_group_app {}
variable ssm_database_password {}
variable ssm_database_urls_writer {}
variable ssm_database_urls_reader {}
variable ssm_assets_urls {}
variable ssm_redis_urls {}
variable ssm_elasticsearch_urls {}
variable ssm_s3_buckets {}
variable ssm_s3_help_buckets {}
variable ecs_app_cpu {}
variable ecs_batch_cpu {}
variable ecs_app_memory {}
variable ecs_batch_memory {}
variable app_desired_count {}
variable batch_desired_count {}
variable asc_app_min_count {}
variable asc_batch_min_count {}
variable asc_app_max_count {}
variable asc_batch_max_count {}
variable asc_app_target {}
variable asc_batch_target {}
variable s3_access_policy_arn {}
variable suffix {}
variable region {}
variable sns_topic {}
variable sns_topic_lambda {}
variable cpu_alert_app_threshold {}
variable memory_alert_app_threshold {}
variable cpu_alert_batch_threshold {}
variable memory_alert_batch_threshold {}
variable rails_max_threads {}
variable rails_database_pool_app {}
variable rails_database_pool_batch {}
