variable "name" {}
variable "vpc_id" {}
variable "vpc_cidr_block" {}
variable "private_subnet_ids" {}
variable "instance_type" {}
variable "ebs_volume_size" {}
variable "host" {}
variable "sns_topic" {}
variable dedicated_master_enabled {}
variable dedicated_master_count {}
variable dedicated_master_type {}
